PUT http://localhost:3003/api/blogs/5a92bca2c1022d328cbd7ab7
Content-Type: application/json

{
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7
}